phpapp:
  image: paintedfox/nginx-php5:latest
  ports:
   - 80:80
  environment:
  # Used if you have an nginx proxypass server
   - VIRTUAL_HOST=phpapp.local
  volumes:
   - data:/data
   - log/nginx:/var/log/nginx